# Project: mid2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.o ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.o
LINKOBJ  = ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.o ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.o
LIBS     = -L"C:/MinGW/lib" -L"C:/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/MinGW/include" -I"C:/MinGW/x86_64-w64-mingw32/include" -I"C:/MinGW/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/MinGW/include" -I"C:/MinGW/x86_64-w64-mingw32/include" -I"C:/MinGW/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
BIN      = mid2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.o: ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.cpp
	$(CPP) -c ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.cpp -o ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2.o $(CXXFLAGS)

../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.o: ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.cpp
	$(CPP) -c ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.cpp -o ../../../../Downloads/OOP_Midterm2/Script/Q2/Q2_main.o $(CXXFLAGS)
